### ISSUE TITLE
Implementing subscriptions

### ISSUE THREAD

**Issue by jakebonk** [aws-samples/aws-mobile-appsync-events-starter-android#1]
All of the other app sync projects have subscription except android, I looked through documentation and noticed the same thing. Is android just on the back burners?

**Comment by rohandubal** [comment]
Hello @jakebonk ,

We are tracking the subscriptions feature [here](https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/1).

I'm closing this issue in favor of tracking in main SDK.

Thanks,
Rohan
