### ISSUE TITLE
Offline persistent data not persisted

### ISSUE THREAD

**Issue by zjye** [aws-samples/aws-mobile-appsync-events-starter-android#2]
I am following the steps by steps guide in the aws appsync, and i cloned the example repository.

In simulator

1) Turn off mobile data
2) Add event
3) Back to the event list
4) Refresh, new Event is not added

Am i missed out any settings?

**Comment by rohandubal** [comment]
Hello @zjye 

Could you please post the code snippet for your mutation operation while offline?

Are you adding it as an optimistic response for the Event List query?

Thanks,
Rohan

**Comment by minbi** [comment]
Hi @zjye ,

I have updated the sample with this use-case. You can see the diff here:
https://github.com/aws-samples/aws-mobile-appsync-events-starter-android/commit/80c7cc50bfa9b95e3146abe0a75045b72b02313c

**Comment by zjye** [comment]
@rohandubal , yeap, i have adding it as optimistic response as well
@minbi , i will give it a try again, thanks.
