### ISSUE TITLE
Unable to update the Cache data 

### ISSUE THREAD

**Issue by nawanirakshit** [aws-samples/aws-mobile-appsync-events-starter-android#4]
I am trying to update the Cache date in the application while the device is offline, so to achieve that I am getting the cache data and then adding a new item inside the list but the data is not visible nor edited.

Below is my code I am using to update the data.

```
    final GetReceivedMessagesQuery.Item selectedItem = list.get(position);
                final GetReceivedMessagesQuery builder = GetReceivedMessagesQuery.builder().receiverId(SharedPreferencesClass.getUserID()).build();

                ClientFactory.getClient().query(builder)
                        .responseFetcher(AppSyncResponseFetchers.CACHE_ONLY)
                        .enqueue(new GraphQLCall.Callback<GetReceivedMessagesQuery.Data>() {
                            @Override
                            public void onResponse(@Nonnull Response<GetReceivedMessagesQuery.Data> response) {
                                List<GetReceivedMessagesQuery.Item> items = new ArrayList<>();
                                items.addAll(response.data().getReceivedMessages().items());

                                GetReceivedMessagesQuery.Item event = new GetReceivedMessagesQuery.Item(selectedItem.__typename(), selectedItem.messageId(), selectedItem.subject(), selectedItem.messageBody(),
                                        selectedItem.parentMessageId(), selectedItem.receiverId(), selectedItem.createdAt(), true, selectedItem.messageRecipient());

                                items.add(event);

                                GetReceivedMessagesQuery.Data data = new GetReceivedMessagesQuery.Data(new GetReceivedMessagesQuery.GetReceivedMessages(selectedItem.__typename(), list, null));
                                ClientFactory.getClient().getStore().write(builder, data).enqueue(null);
                            }

                            @Override
                            public void onFailure(@Nonnull ApolloException e) {
                                Log.e("onFailure", "Failed to update event query list.", e);
                            }
                        });
```
is there any other way to update the Object locally without having an active internet connection?
Any help is appreciable Thanks in advance

**Comment by rohandubal** [comment]
This example in the sample app demonstrates writing in local store:
https://github.com/aws-samples/aws-mobile-appsync-events-starter-android/blob/master/app/src/main/java/com/amazonaws/demo/appsync/AddEventActivity.java#L146

Does the sample app example work for you?

Do you get any error? What version of SDK you are using?

Thanks,
Rohan

**Comment by nawanirakshit** [comment]
Thank you for the reply 

I am using **compileSdkVersion** and **targetSdkVersion** is 27

The sample code snippet I added above is **not adding a new item to the list**, the flow is going inside the **onResponse** and not inside the **onFailure**

and if I try to add the callback for the write method it is giving me error as the **GraphQLStoreOperation.Callback** interface is not public. 

```
   ClientFactory.getClient().getStore().write(builder, data).enqueue(new GraphQLStoreOperation.Callback<Set<String>>() {   //error here
                                    @Override
                                    public void onSuccess(Set<String> result) {

                                    }

                                    @Override
                                    public void onFailure(Throwable t) {

                                    }
                                });
                            }

                            @Override
                            public void onFailure(@Nonnull ApolloException e) {
                                Log.e("onFailure", "Failed to update event query list.", e);
                            }
                        });
```


and the **AddEventActivity.addToListEventsQuery** is writing a new item in the list is there any way I can update the already available data in the list?

**Comment by minbi** [comment]
You may use optimistic updates to change existing items.
[Documentation](https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-android.html#optimistic-updates)

Inline below:

This section makes changes to the UpdatePostActivity.save() method that was created in the previous step.

For optimistic updates, create the data expected to be returned after the mutation. The optimistic updates are written to the persistent SQL store.

Note that the UpdatePostMutation class is the same class used to create the expected object as well as make the mutation request.

```
UpdatePostMutation.Data expected = new UpdatePostMutation.Data(new UpdatePostMutation.PutPost(
    "Post",
    sPost.id(),
    author,
    title,
    content,
    url,
    sPost.version() + 1)
);
```

The mutation call will now become the the following, which takes in the expected data:

```
UpdatePostMutation.Data expected = new UpdatePostMutation.Data(new UpdatePostMutation.PutPost(
    "Post",
    sPost.id(),
    author,
    title,
    content,
    url,
    sPost.version() + 1)
);

UpdatePostMutation updatePostMutation = UpdatePostMutation.builder()
        .input(UpdatePostInput.builder()
                .id(sPost.id())
                .title(title)
                .author(author)
                .url(url)
                .content(content)
                .ups(sPost.ups())
                .downs(sPost.downs())
                .version(sPost.version() + 1)
                .build())
        .build();

// Make mutation call
ClientFactory.getInstance(this).mutate(updatePostMutation, expected).enqueue(postsCallback);
//                                                         ^^^^^^^^
```

**Comment by nawanirakshit** [comment]
Thanks for the reply @minbi 
Please do correct me if I am wrong 
The documentation you mentioned will work on the operation Mutation part correctly but I think the above functionality will not work on the operation Query part.

I need to update the **response** which I get from the operation Query and also send a new mutation operation request to update the data to the DynamoDB

**Comment by minbi** [comment]
The local database will read the data from the same item. The response of a query served by the cache should have the data from the mutation.

**Comment by nawanirakshit** [comment]
Hi @minbi Thank you for the information
I would like to know that

If I had my Query operation data with me and let suppose it has a list of 5 items and I want to update the 3rd element inside it so how can I do this as I am unable to find this in the documentation.

**Comment by minbi** [comment]
The data is organized by a cache key. This is generally the `id` field of the item. Then use the mutation format shown in a previous post to mutate (change) the item.

**Comment by richienko** [comment]
This is not working for me either, although I'm only updating data.

Steps (query all items is done with AppSyncResponseFetchers.NETWORK_FIRST setting):
1. while online, query all items
2. go offline, edit data, apply mutation with optimistic update
3. while offline, query all items -> data are same as before edit

my code:
```
job.setDueDate(et_due_date.getText().toString());
job.setWindowStart(ed_window_start.getText().toString());
job.setWindowEnd(ed_window_end.getText().toString());
job.setStatus(et_state.getText().toString());

UpdateJobMutation.Data updateJobMutationExpected = new UpdateJobMutation.Data(
		new UpdateJobMutation.UpdateJob("Job",
				job.getId(),
				job.getCustomerId(),
				job.getAssignedEntityId(),
				job.getTourId(),
				job.getDueDate(),
				job.getWindowStart(),
				job.getWindowEnd(),
				job.getStatus()));

UpdateJobMutation updateJobMutation = UpdateJobMutation.builder().input(UpdateJobInput.builder()
		.id(job.getId())
		.customerId(job.getCustomerId())
		.assignedEntityId(job.getAssignedEntityId())
		.tourId(job.getTourId())
		.dueDate(job.getDueDate())
		.windowStart(job.getWindowStart())
		.windowEnd(job.getWindowEnd())
		.status(job.getStatus())
		.build()).build();

ClientFactory.getInstance(getApplicationContext()).mutate(updateJobMutation, updateJobMutationExpected).enqueue(jobsCallback);

boolean isConnected = ConnectionChecker.hasConnectivity(getApplicationContext());

if (!isConnected) {
	JobDetailActivity.this.setResult(Activity.RESULT_OK);
	JobDetailActivity.this.finish();
}
```

`job` object is just Parcelable JBOD for transfering data between activities.

**Comment by richienko** [comment]
I got it working with CACHE_ONLY response fetcher.

**Comment by minbi** [comment]
The `AppSyncResponseFetchers.CACHE_AND_NETWORK` would also be appropriate.
